# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc209f2e4714a48e49d1395fcebc907621c7bcf3e796ff114c0e60defdd499d2130d32cb8672eab294d0409fe48c5514fd5a0170514d2ea5b8757218c8ffe84

test:
  secret_key_base: 00d9bda521b7c1c6388b8d999b0ae88db4f6cc2adba2f081cf744471b0e563f3d4c98c6021a01566b5fc3b9c084279866a5920d9f2aaa358a670092dee73908d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
